[tool.bumpver]
current_version = "2.23.0"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit_message = "chore: Bump version {old_version} -> {new_version}"
commit = true
fetch = true
tag = true
push = true

[tool.bumpver.file_patterns]
"readme.txt" = ['Stable tag: {version}']
"tillit-payment-gateway.php" = ['Version: {version}']
