version: '3.1'

services:

  wordpress:
    container_name: wordpress
    extra_hosts:
      - "portal.localhost:host-gateway"
    image: ${REPO}wordpress:latest
    restart: always
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: twocommerce
      WORDPRESS_DB_PASSWORD: twocommerce
      WORDPRESS_DB_NAME: twocommerce
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./volumes/log/:/var/log/apache2/
    depends_on:
      - mariadb

  wpcli:
    container_name: wpcli
    image: ${REPO}wordpress:cli
    user: "33:33"
    entrypoint: /opt/tillit-payment-gateway/entrypoint.sh
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: twocommerce
      WORDPRESS_DB_PASSWORD: twocommerce
      WORDPRESS_DB_NAME: twocommerce
      WORDPRESS_URL: "http://localhost:8888"
      WORDPRESS_TITLE: "Twocommerce Wordpress"
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: twoinb2b
      WORDPRESS_ADMIN_EMAIL: admin@two.inc
      WOOCOM_CURRENCY: GBP
      WOOCOM_CONFIG_JSON: ${WOOCOM_CONFIG_JSON}
    volumes:
      - ./volumes/wordpress:/var/www/html
      - .:/opt/tillit-payment-gateway
    depends_on:
      - mariadb
      - wordpress

  mariadb:
    container_name: mariadb
    image: ${REPO}mariadb:10.2
    restart: always
    environment:
      MARIADB_DATABASE: twocommerce
      MARIADB_USER: twocommerce
      MARIADB_PASSWORD: twocommerce
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
