serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7000
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

transport.tls.enable = true
transport.poolCount = 10

[[proxies]]
localPort = {{ .Envs.PORT }}
name = "{{ .Envs.SUBDOMAIN }}"
type = "http"
localIP = "{{ .Envs.HOST }}"
customDomains = ["{{ .Envs.FRP_DOMAIN }}"]
